version: '2'
services:
    marviva-app:
        image: marviva
        external_links:
            - marviva-postgresql:postgresql
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/marviva
        ports:
            - 8080:8080
    marviva-postgresql:
        extends:
            file: postgresql.yml
            service: marviva-postgresql
